### PR TITLE
build(deps): bump arcgis packages to 4.33

### PR DESCRIPTION
**Pull request by benelan**
**Related Issue:** #11536

## Summary

- Bump Node to `v22`
- Add an `.nvmrc` version file to prevent conflicts with Volta
- Fix browser/node inconsistency with the Hebrew meridiem (it stopped working in Node `v20.19` for some reason). Running [this code] in Node `v22` prints:
    > AM: AM
    > PM: PM
- Move `vitest` and `@vitest/browser` devDeps from the monorepo root to the the packages that use them
- Bump `@arcgis/*` packages to the `next` version of `4.33`.

> [!NOTE]
> Bumping Node to `v22` causes a [`github-script`] warning during `npm install`, which can be ignored since the package is only [used for types].
>
> ```text
> npm warn EBADENGINE Unsupported engine {
> npm warn EBADENGINE   package: 'github-script@7.0.1',
> npm warn EBADENGINE   required: { node: '>=20.0.0 <21.0.0' },
> npm warn EBADENGINE   current: { node: 'v22.13.0', npm: '10.9.2' }
> npm warn EBADENGINE }
> ```

[`github-script`]: https://github.com/actions/github-script
[this code]: https://codepen.io/benelan-dev/pen/pvvypry?editors=0012
[used for types]: https://github.com/actions/github-script/tree/main#use-scripts-with-jsdoc-support

### CODE REVIEW

**Comment by benelan** [comment]
@maxpatiiuk are these type errors expected, do we need to change something on our end?

```
src/components/tree/tree.e2e.ts:509:32 - error TS2339: Property 'toHaveReceivedEventTimes' does not exist on type 'Assertion<EventSpy<unknown>>'.

509         expect(selectEventSpy).toHaveReceivedEventTimes(0);
                                   ~~~~~~~~~~~~~~~~~~~~~~~~

src/components/tree/tree.e2e.ts:512:25 - error TS2339: Property 'toHaveAttribute' does not exist on type 'Assertion<E2EElement>'.

512         expect(parent1).toHaveAttribute("indeterminate");
                            ~~~~~~~~~~~~~~~
```

**Comment by maxpatiiuk** [comment]
Move or copy @vitest/browser from root package.json into the one into calcite-components. That way, lumina.ts well include the necessary references for packages you used. Same for "vitest"

**Comment by maxpatiiuk** [comment]
Looks like you have multiple vitest versions installed:
image

Lumina define additional vitest matchers and extents type script typing for them (per vitest docs: https://vitest.dev/guide/extending-matchers.html#extending-matchers:~:text=If%20you%20are%20using%20TypeScript)
But this only works correctly if you have a single version of vitest

fyi we are in the process of updating all lumina dependencies: https://devtopia.esri.com/WebGIS/arcgis-web-components/pull/4477

**Comment by benelan** [comment]
Thanks for the help @maxpatiiuk! Making progress, but now there's a new error:

```
error during build:
[@arcgis/lumina:buildCdn] s.entries(...).map is not a function
    at uc (file:///home/runner/work/calcite-design-system/calcite-design-system/node_modules/@arcgis/lumina-compiler/dist/index.js:4823:37)
    at Object.writeBundle (file:///home/runner/work/calcite-design-system/calcite-design-system/node_modules/@arcgis/lumina-compiler/dist/index.js:4735:15)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async Promise.all (index 7)
    at async PluginDriver.hookParallel (file:///home/runner/work/calcite-design-system/calcite-design-system/node_modules/rollup/dist/es/shared/node-entry.js:22066:9)
    at async file:///home/runner/work/calcite-design-system/calcite-design-system/node_modules/rollup/dist/es/shared/node-entry.js:23140:13
    at async catchUnfinishedHookActions (file:///home/runner/work/calcite-design-system/calcite-design-system/node_modules/rollup/dist/es/shared/node-entry.js:22508:16)
    at async build (file:///home/runner/work/calcite-design-system/calcite-design-system/node_modules/vite/dist/node/chunks/dep-DbT5NFX0.js:65649:16)
    at async CAC.<anonymous> (file:///home/runner/work/calcite-design-system/calcite-design-system/node_modules/vite/dist/node/cli.js:829:5)
```

Have you seen that one?

**Comment by maxpatiiuk** [comment]
Lumina requires Node v22, same as JSAPI and AWC
We have a check for this within AWC – I will open an issue to have this check work outside too

File: .nvmrc [hunk 1]
```diff
@@ -0,0 +1 @@
+22.14.0
```
Comment (jcfranco) [inline .nvmrc:1]: Side note: is there a way we could automate this being in sync w/ `package.json`?

**Review by jcfranco — APPROVED** [review]
🚀

File: .nvmrc (hunk 1 above)
Comment (benelan) [reply .nvmrc:1]: I think renovate will bump the version in `.nvmrc` and the `volta` field in `package.json` - https://docs.renovatebot.com/node/
